{% set name = "minio-server" %}
{% set version = "RELEASE.2024-12-18T13-15-44Z" %}
{% set sha256 = "d7d044f11a343389b1952c48a3e15feef6efa63c67b9f025c212a04016f05037" %}
{% set time = version|replace("RELEASE.", "") %}

package:
  name: {{ name|lower }}
  version: {{ time|replace("-", ".")|replace("T", ".")|replace("Z", "") }}

source:
  url: https://github.com/minio/minio/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # patch gen-ldflags.go to not use `git` to detect the git commit hash
    # instead use GitHub API (see build/script_env/GIT_TAG and GIT_COMMIT in build scripts)
    - patches/0001-commitID.patch

build:
  number: 0
  script_env:
    - GIT_TAG={{ version }}
    - GIT_TIME={{ time }}

requirements:
  build:
    - "{{ compiler("go-nocgo") }} >=1.16"
    - curl
    - go-licenses
    - jq  # [not win]
    - m2w64-jq  # [win]

test:
  commands:
    - minio --version

about:
  home: https://min.io
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - library_licenses/
    - manual_licenses/
  summary: High Performance Object Storage for AI
  description: |
    MinIO is a High Performance Object Storage released under GNU Affero General Public License v3.0.
    It is API compatible with Amazon S3 cloud storage service. Use MinIO to build high performance
    infrastructure for machine learning, analytics and application data workloads.
  doc_url: https://min.io/docs/minio
  dev_url: https://github.com/minio/minio

extra:
  recipe-maintainers:
    - kenodegard
    - pavelzw
